server {
    listen 80;
    server_name _;
    root /usr/share/nginx/html;
    index index.html;
    # Clave para SPAs (React Router):
    location / {
        try_files $uri $uri/ /index.html;
    }
    # Cache de assets estáticos
    location ~* \.(js|css|png|jpg|jpeg|gif|ico|svg)$ {
        expires 6M;
        add_header Cache-Control "public";
    }
}
